#!/bin/bash 


printf "=========================================================================\n"
printf "                             Add New A Domain\n"
printf "=========================================================================\n"
echo -n "Type the user contain list domain or leave null for set /home folder  and press [ENTER]: "
read user
echo -n "Type the domain name and press [ENTER]: "
read domain
if [ "$domain" = "" ]; then
echo "Incorrect, please try again"
exit
fi
if [ "$user" = "" ]; then
domain_path="$domain"
else
domain_path="$user/$domain"
fi

if [ -f /etc/nginx/sites-enabled/$domain.conf ]; then
echo "$domain already exist"
echo "Bye...!"
exit
fi
    mkdir -p "/home/$domain_path/public_html"
    mkdir -p "/home/$domain_path/logs"
    
    cp -p /etc/tdc/action/index.html /home/$domain/public_html/index.html
    
    chown www-data:www-data /home/$domain_path
    chown -R www-data:www-data /home/*/public_html
    chown -R www-data:www-data /var/lib/php
    
    domain_alias="www.$domain"
    if [[ $domain == *www* ]]; then
	    domain_alias=${domain/www./''}
    fi

    cat > "/etc/nginx/sites-enabled/$domain.conf" <<END
server {
	listen 80;
	
	server_name $domain_alias;
	rewrite ^(.*) http://$domain\$1 permanent;
}

server {
	listen 80;

    	# access_log off;
	access_log /home/$domain_path/logs/access.log;
    	# error_log off;
    	error_log /home/$domain_path/logs/error.log;
	
    	root /home/$domain_path/public_html;
	index index.php index.html index.htm;
    	server_name $domain;
 
    	location / {
		try_files \$uri \$uri/ /index.php?\$args;
	}
	
	# Custom configuration
	include /home/$domain_path/public_html/*.conf;
 
    	location ~ \.php$ {
		    fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include /etc/nginx/fastcgi_params;
            fastcgi_pass unix:/run/php/php7.0-fpm.sock;
            fastcgi_index index.php;
		    fastcgi_connect_timeout 300;
		    fastcgi_send_timeout 300;
		    fastcgi_read_timeout 300;
		    fastcgi_buffer_size 32k;
            fastcgi_buffers 8 16k;
            fastcgi_busy_buffers_size 32k;
            fastcgi_temp_file_write_size 32k;
            fastcgi_intercept_errors on;
        	fastcgi_param SCRIPT_FILENAME /home/$domain_path/public_html\$fastcgi_script_name;
    	}
	
	location ~ /\. {
		deny all;
	}
	
	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}
	
	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}
	
	location ~* \.(3gp|gif|jpg|jpeg|png|ico|wmv|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|eot|svg|ttf|woff)$ {
		gzip_static off;
		add_header Pragma public;
		add_header Cache-Control "public, must-revalidate, proxy-revalidate";
		access_log off;
		expires 30d;
		break;
        }

        location ~* \.(txt|js|css)$ {
	        add_header Pragma public;
		add_header Cache-Control "public, must-revalidate, proxy-revalidate";
		access_log off;
		expires 30d;
		break;
        }
}
END
    service nginx reload

echo "Created successfully $domain"
echo "Upload code to /home/$domain_path/public_html/"
echo "Log of $domain show in /home/$domain_path/logs"